### ISSUE TITLE
Root CA

### ISSUE THREAD

**Issue by ltf0925** [vslepakov/keyvault-ca#27]
Hi sir, 

     I am working on a 802.1AR root CA project which will be based on Azure key vault. By accident I came across this project and went through the project with a limited knowledge of Azure key vault and dotnet. 

 I roughly understand how a self-signed root CA is created in the project: 
1. create a temporary self-signed certificate in Azure key vault and export its private key;  
2. create a CSR with the same certificate name in Azure key vault and sign the CSR with the private key exported in the first step and merge to Azure key vault.  A self-signed root CA certificate  is saved in Azure key vault. 

I am wondering how the two certificates ( the temporary self-signed certificate  in step 1 and the self-signed root CA certificate in step2) have the same key pairs?  Do I miss some point in the use of Azure key vault?

thanks

Tim

**Comment by vslepakov** [comment]
Hi @ltf0925,

the flow is a bit different:

1. Create a self-signed certificate in Azure KeyVault (we are interested in the key pair).
2. Get the resulting certificate bundle to access cert Id and key identifiers. Note the private key never leaves Azure KeyVault, instead we only use the reference to the private key (key id) to instruct Azure KeyVault to use this key for signing in step 4. This is the main purpose of the first operation: let KeyVault create and store a key pair.
3. When we make the second call to `StartCreateCertificateAsync` [here](https://github.com/vslepakov/keyvault-ca/blob/master/KeyVaultCa.Core/KeyVaultServiceClient.cs#L89C61-L89C88) as per [documentation](https://learn.microsoft.com/en-us/dotnet/api/azure.security.keyvault.certificates.certificateclient.startcreatecertificateasync?view=azure-dotnet#remarks) it will create a new version of the same certificate (with "Unknown" issuer so we can merge later) since Azure KeyVault already knows the Id.
4. Then we create a proper structure for our Root Certificate [here](https://github.com/vslepakov/keyvault-ca/blob/master/KeyVaultCa.Core/KeyVaultServiceClient.cs#L111) instructing Azure KeyVault to use the private key it generated in step 1 to sign this certificate structure (by passing in a `X509SignatureGenerator `).
5. Now we have a signed Root Certificate and [merge](https://github.com/vslepakov/keyvault-ca/blob/master/KeyVaultCa.Core/KeyVaultServiceClient.cs#L126) it with the key pair from step 1. Note that we use the same cert id thus referring to and operating on the same object (with multiple versions) in Azure KeyVault.

I guess, if you would want to do this in the portal, it would look something like [this](https://learn.microsoft.com/en-us/azure/key-vault/certificates/create-certificate-signing-request?tabs=azure-portal#add-certificates-in-key-vault-issued-by-non-partnered-cas) with the exception that we are not using an external CA to sign the cert but rather use the key generated by Azure KeyVault in step 1 to do this.

Here is some [additional information](https://learn.microsoft.com/en-us/azure/key-vault/certificates/create-certificate#self-issued-certificate). In step 1 Azure KeyVault will reuse the cert subject in the issuer field (self-signed). We change it to "Unknown" to be able to 

> merge the public x509 certificate with the key vault certificate pending object to complete the certificate creation

**Comment by ltf0925** [comment]
Thank you for your great comments!

Tim
